spring.application.name=MorphCode
spring.application.description=MorphCode is a Spring Boot-based code generation that morphs to your intentions, providing a seamless and efficient way to generate code based on your specifications.
spring.application.version=1.0.0

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:9000/testDB2
spring.datasource.username=testAyush
spring.datasource.password=testpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
